### ISSUE TITLE
unrecognized arguments: --low

### ISSUE THREAD

**Issue by lorenzb** [trailofbits/slither#1]
The readme says that there is a `--low` flag, but when I try it I get an error:
```bash
$ ./slither.py ../onchain/ProvethVerifier.sol --low
usage: slither.py contract.sol
slither.py: error: unrecognized arguments: --low
```

Also, it might be nice to change the usage line of the help to
```
usage: slither.py contract.sol [flags]
```
I initially assumed that flags go before the file to be analyzed.

**Comment by montyly** [comment]
Thank you for the issue!

It should be fixed in https://github.com/trailofbits/slither/commit/f47c4385db33c09d26e3dc67b20d58ec80995f91

Note that the current public version of slither has only one detector available on it. Tutorials and more detectors are coming
