### ISSUE TITLE
Add functionality to exclude specific tests

### ISSUE THREAD

**Issue by dguido** [trailofbits/slither#10]
I don't think the --high, --medium, --low flags make a ton of sense right now. As a user, it's more common that one or more noisy checks are false positives and I want to disable them specifically. We should add some notion of IDs to each check, then have a single flag like `--exclude reentrancy` or similar to turn it off for that run.

**Comment by montyly** [comment]
Fixed in https://github.com/trailofbits/slither/commit/d7e15590dfdb07839ed1d2b012206394ad434faf
Any detector can now be excluded with `--exclude-name`
It is also possible to exclude a category of detectors, e.g. `--exclude-informational`
