### ISSUE TITLE
KeyError: 2157

### ISSUE THREAD

**Issue by alicevhenshaw** [trailofbits/slither#103]
INFO:Slither:truffle compile running...
INFO:Slither:
ERROR:root:Error in .
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/slither/__main__.py", line 229, in main_impl
    (results, number_contracts) = process_truffle(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.7/site-packages/slither/__main__.py", line 90, in process_truffle
    slither = Slither(all_contracts, args.solc, args.disable_solc_warnings, args.solc_args)
  File "/usr/local/lib/python3.7/site-packages/slither/slither.py", line 41, in __init__
    self._analyze_contracts()
  File "/usr/local/lib/python3.7/site-packages/slither/solc_parsing/slitherSolc.py", line 164, in _analyze_contracts
    fathers.append(self._contracts_by_id[i])
KeyError: 2157

**Comment by montyly** [comment]
Hi, 
Thanks for the report.

This issue is usually related to an internal bug in truffle (see https://github.com/trailofbits/slither/wiki#keyerror-or-nonetype-error), that occurs if two contracts share the same name, or if two file shares the same filename. 

Could you share the source code, or check if it is the case?

**Comment by alicevhenshaw** [comment]
It wasn't the case but I know the truffle build folder stores things from previous builds that are no longer relevant. I've deleted the old build folder and rebuilt from scratch and now slither works.

Thanks!

**Comment by yvesbou** [comment]
deleting artifacts and cache folder from hardhat project helped me with key error 2394 https://ethereum.stackexchange.com/questions/131264/slither-keyerror-2394/131265#131265
