### ISSUE TITLE
Add local truffle compile alternative

### ISSUE THREAD

**Issue by mattaereal** [trailofbits/slither#105]
Currently slither does runs `truffle compile` before running.
If there is no system or global truffle installed, it fails:
```
matt@delleite:audit/ (master*) $ slither . 
INFO:Slither:truffle compile running...
ERROR:root:Error in .
ERROR:root:Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/slither_analyzer-0.3.1-py3.7.egg/slither/__main__.py", line 229, in main_impl                                                          
    (results, number_contracts) = process_truffle(filename, args, detector_classes, printer_classes)                                                                            
  File "/usr/lib/python3.7/site-packages/slither_analyzer-0.3.1-py3.7.egg/slither/__main__.py", line 64, in process_truffle                                                     
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1516, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'truffle': 'truffle'
```
Add the option to run `npx truffle compile` instead of just `truffle compile`.

**Comment by montyly** [comment]
Thanks for you contribution @mattaereal 

I slightly changed the format of your PR, the flag is named `--truffle-version` and takes an argument.

The goal is to also allow any version of truffle to be run.

For example you can run
`slither  --truffle-version truffle@beta .` 
To run with Truffle v5 (which uses Solidity 0.5)

Or
`slither  --truffle-version truffle@4.1.14 .`
If you want to use truffle v4 (which uses Solidity 0.4.25)

Note that `slither --truffle-version truffle .` will also work.

**Comment by mattaereal** [comment]
Excellent. The main idea behind the "local" run, was to use current project's truffle version, but there may be projects that aren't configured correctly or you may opt to use one in top of another.

Thanks for merging :)
