### ISSUE TITLE
Add non-security style/linting checks

### ISSUE THREAD

**Issue by dguido** [trailofbits/slither#11]
https://github.com/duaraghav8/Solium
https://github.com/protofire/solhint

**Comment by samparsky** [comment]
@dguido can you shed more light on this issue?

**Comment by dguido** [comment]
@montyly Can you file individual issues for non-security checks you'd like to see contributed?

**Comment by montyly** [comment]
hey @samparsky , thanks for your interest in slither.

I created several issues with the label `help wanted`.

I also updated the [detector documentation](https://github.com/trailofbits/slither/wiki/Adding-a-new-detector).

Dont hesitate to join [our slack](https://empireslacking.herokuapp.com) (#ethereum) if you have any questions.

**Comment by dguido** [comment]
I am going to close this issue in favor of the individual ones that we filed
