### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'is_analyzed'

### ISSUE THREAD

**Issue by WyseNynja** [trailofbits/slither#123]
```
$ slither .
ERROR:root:Error in .
ERROR:root:Traceback (most recent call last):
  File "/root/.local/venvs/slither-analyzer/lib/python3.6/site-packages/slither/__main__.py", line 241, in main_impl
    (results, number_contracts) = process_truffle(filename, args, detector_classes, printer_classes)
  File "/root/.local/venvs/slither-analyzer/lib/python3.6/site-packages/slither/__main__.py", line 81, in process_truffle
    return process_files(filenames, args, detector_classes, printer_classes)
  File "/root/.local/venvs/slither-analyzer/lib/python3.6/site-packages/slither/__main__.py", line 91, in process_files
    slither = Slither(all_contracts, args.solc, args.disable_solc_warnings, args.solc_args)
  File "/root/.local/venvs/slither-analyzer/lib/python3.6/site-packages/slither/slither.py", line 41, in __init__
    self._analyze_contracts()
  File "/root/.local/venvs/slither-analyzer/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 179, in _analyze_contracts
    self._analyze_all_enums(contracts_to_be_analyzed)
  File "/root/.local/venvs/slither-analyzer/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 213, in _analyze_all_enums
    all_father_analyzed = all(father.is_analyzed for father in contract.inheritance)
  File "/root/.local/venvs/slither-analyzer/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 213, in <genexpr>
    all_father_analyzed = all(father.is_analyzed for father in contract.inheritance)
AttributeError: 'NoneType' object has no attribute 'is_analyzed'
```

I created the [contract json](https://gist.github.com/WyseNynja/393dcb483e45797f88960a62271689a9) in a [very non-standard way](https://github.com/ethereum/solidity/issues/5758), so I'm sure that is at the heart of the issue. It is probably missing a section since I only include the abi, ast, and bytecode. What else does slither need?

**Comment by montyly** [comment]
The issue is that the json you manually created is missing a part of the code.

If you look at the inheritance of `GasToken2`:
```
        "linearizedBaseContracts": [
          536,
          722
        ],
```
- `536` is the id of `GasToken2`
- `722` is the id of `Rlp`, but the its definition is not present in the json

Slither needs access to all the source code to work, so you need to add the definition of `Rlp`.
If you compile both contracts separately, the id generated may differ (the AST of `Rlp` can give an id different than 722), so you will need to manually update them. 

Out of curiosity, is there a particular reason from crafting the json manually?

**Comment by WyseNynja** [comment]
I used truffle to build the JSON as an external compile step. I need an older compiler for this contract than the one my own contracts are using. 

Can you recommend a better way to build this JSON?

**Comment by montyly** [comment]
Could you share the code that your are trying to analyze?

I am not sure to understand why you need a manual json editing. 

If your project is a truffle project, running `slither .` on top of the truffle directory will be enough. I would recommend deleting the `build` directory before running slither, in case you have manually edited files in it.

**Comment by WyseNynja** [comment]
My project is a truffle project. The problem is that I'm also including other projects that aren't truffle projects and I need to build them, too.

I'm not manually editing JSON. Truffle is doing that part. I'm just passing output from solc to truffle like I thought I was supposed to.

More detail here: https://github.com/trufflesuite/truffle/issues/1607

**Comment by montyly** [comment]
I see!

I am not entirely sure about the error:
```
  File "/root/.local/venvs/slither-analyzer/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 69, in _parse_contracts_from_loaded_json
    if data_loaded[self.get_key()] == 'root':
KeyError: 'nodeType'
```

Is it possible that the generated json mixes the solc compact ast format with the legacy one? If it folows only the compact ast format, each node should have a `nodeType` item (and so `data_loaded` should have it too)

If you have a minimal codebase that produces the same error, I can try to reproduce it

**Comment by WyseNynja** [comment]
Oh, so we do want `--ast-compact-json` and not `--ast-json`. I'll put it back to that and see what happens. If that doesn't work, I'll push my repo to GitHub so you can take a look.

Thanks for the help!

**Comment by montyly** [comment]
Could you check that all the ids in the `linearizedBaseContracts` items of the json refer to a `ContractDefinition` node id?

**Comment by WyseNynja** [comment]
I'm pretty new to this, but I think the definition for rlp is missing. I guess adding rlp.sol to the end of my solc command isn't enough.

https://gist.github.com/WyseNynja/e76a61f1564650ba34a037648d5fcc60

**Comment by montyly** [comment]
I am able to have slither working, but its a bit tricky:
- In an empty directory, run `touch truffle.js` and create a subdirectory `build/contracts`
- Copy `GasToken2.json` file to `build/contracts`
- Extract the json from rlp.sol: `solc-0.4.25 rlp.sol  --ast-compact-json > rlp.json`
- Edit `rlp.json`:
    - Change the id of the contract to 722, (it should be at lines 11, 36, and 39)
    - Add an extra `}` at the end of the file
    - Replace the header 
```
JSON AST (compact format):


======= ../rlp.sol =======
```
by
```
{
"sourcePath":"rlp.sol",
```
- Copy `rlp.json` to `build/contracts`
- Run `slither .` 

Truffle should generate the `rlp.json` file automatically, but maybe it does not as you provide an extra compilation step (and you use two different compiler versions)

**Comment by WyseNynja** [comment]
That is certainly trickier than I was hoping for.  Your directions pointed me to a typo that got it working though! A bad copy/paste had me using the same ast file for both GST2 and rlp.

./scripts/build-external.sh
```
#!/bin/bash -eu
echo "Building external contracts..."

# TODO: only run if they are outdated

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

root_dir="$(realpath "${script_dir}/../")"

build_dir="${root_dir}/build"

external_dir="${root_dir}/external"

# clearing old builds
# TODO: move to a temp dir instead?
echo "Clearing old builds..."
rm -rf "${build_dir}"
mkdir -p "${build_dir}"

# gastoken
echo "Building gastoken..."
# TODO: I think we are missing some more flags here (https://github.com/trailofbits/slither/issues/123)
gastoken_contract_dir="${external_dir}/gastoken/contract"
solc-0.4.25 \
    --allow-paths "${gastoken_contract_dir}" \
    --optimize \
    --output-dir "${build_dir}/gastoken" \
    --abi --ast-compact-json --bin \
    "=${gastoken_contract_dir}/" \
    "${gastoken_contract_dir}/"{GST2_ETH,rlp}.sol

for bin in "${build_dir}/"*"/"*.bin; do
    bin_dir=$(dirname -- "$bin")
    filename=$(basename -- "$bin")
    filename="${filename%.*}"

    # bin output needs to be prefixed with 0x for truffle to like it
    (echo -n "0x"; cat "$bin") > "${bin_dir}/${filename}.truffle-bin"
done

echo "Success building external contracts"
```

truffle-config.js
```
module.exports = {
  ...
  compilers: {
    external: {
      command: "./scripts/build-external.sh",
      targets: [
        {
          properties: {
            contractName: "GasToken2",
          },
          fileProperties: {
            abi: "build/gastoken/GasToken2.abi",
            ast: "build/gastoken/GST2_ETH.sol_json.ast",
            bytecode: "build/gastoken/GasToken2.truffle-bin",
          },
        },
        {
          properties: {
            contractName: "rlp",
          },
          fileProperties: {
            abi: "build/gastoken/rlp.abi",
            ast: "build/gastoken/rlp.sol_json.ast",
            bytecode: "build/gastoken/rlp.truffle-bin",
          },
        },
      ],
    },
...
```

```
$ yarn slither .
...
INFO:Slither:. analyzed (19 contracts), 75 result(s) found
```

I have a feeling that my truffle-config.js is going to get pretty long if I have to do this for all the upstream projects. Luckily 0x has a very helpful migrate script that I can use instead of manually compiling like I'm doing for gastoken.
