### ISSUE TITLE
Unimplemented function.is_empty is None when it should be True

### ISSUE THREAD

**Issue by Xenomega** [trailofbits/slither#124]
When a function is unimplemented, it will have the `is_empty` property as `None` (as `_parse_cfg` was never hit to set the underlying value). 

This is undesirable as a check such as `if function.is_empty:` will yield false, as if it has a body. One of the existing detectors currently has a check like this, and has some false-negatives as a result.

By default we should set `_is_empty` to True instead of `None`, to avoid such error in the future.

```
interface A {
    function f() public;
    function g() public;
}

contract B is A {
    function f() public {
        uint x = 1;
    }
}
```
In the above example, the function `g` has property `is_empty` set as None.

**Comment by montyly** [comment]
I am not sure about this change, for empty functions there are three cases:
- The function is implemented and has a body: return `True`
- The function is implemented and has no body: return `False`
- The function is not implemented (it's just an interface): return `None`

The current documentation of `is_empty` states that `is_empty` is None for interfaces:

https://github.com/trailofbits/slither/blob/fc4ac0c988ef098cf06b8b934e70b4b39abd8a12/slither/core/declarations/function.py#L153-L158

Empty function is a specific set of function with no body, they are typically payable function receiving ethers (like `receiveFunds`). Adding interfaces to this set might be unexepcted.

Note that there is an additional property, `is_implemented` which returns `True` if the function is implemented, and `False` if not

https://github.com/trailofbits/slither/blob/fc4ac0c988ef098cf06b8b934e70b4b39abd8a12/slither/core/declarations/function.py#L146-L151

Any thoughts?  Maybe `is_empty` is not the best name

**Comment by Xenomega** [comment]
Ah. I missed that. If this has purposefully been done, then we should probably leave it and just fix the affected detector. I just figured initially such behavior could make naive usage more error prone.
