### ISSUE TITLE
virtualenvwrapper.sh: There was a problem running the initialization hooks.

### ISSUE THREAD

**Issue by sriharikapu** [trailofbits/slither#128]
```
Macs-MacBook-Pro:slither sriharikapu$ source /usr/local/bin/virtualenvwrapper.sh
/usr/bin/python: No module named virtualenvwrapper
virtualenvwrapper.sh: There was a problem running the initialization hooks.

If Python could not import the module virtualenvwrapper.hook_loader,
check that virtualenvwrapper has been installed for
VIRTUALENVWRAPPER_PYTHON=/usr/bin/python and that PATH is
set properly.

```

**Comment by montyly** [comment]
Thanks for the report @sriharikapu .

I can't reproduce the bug, but I am assuming it's because you are on a macos? 
Did you manage to find a workaround?

**Comment by montyly** [comment]
As we don't have news, I am assuming @sriharikapu found a way to have virtualenvwrapper working with its setup.

**Comment by Lumi1717** [comment]
I have the same problem....
Can anyone help me

**Comment by montyly** [comment]
Hi @Lumi1717,

Could you give some details on your configuration? What OS are you running? What version of python are you using?

**Comment by sriharikapu** [comment]
@montyly It occurs in OS's which are of Darwin architecture. And that too happens if you have multiple versions of Pythons installed in your machine.

**Comment by montyly** [comment]
Could you try to set the `VIRTUALENVWRAPPER_PYTHON` before running `source /usr/local/bin/virtualenvwrapper.sh`?

For example:
```
VIRTUALENVWRAPPER_PYTHON='/usr/bin/python3'
source /usr/local/bin/virtualenvwrapper.sh
```

This is an issue with virtualenvwrapper. I would recommend opening a ticket to the tool's tracker: https://bitbucket.org/virtualenvwrapper/virtualenvwrapper/issues?status=new&status=open

In case you do not plan to develop on top of Slither's API, I would recommend to not use virtualenv, and directly install Slither with:
```
pip3 install slither-analyzer
```

**Comment by sriharikapu** [comment]
@montyly I moved out of darwin OS so I am free now. I don't have any issues anymore. Let @Lumi1717 check it and let you know..

**Comment by JamesDeLay** [comment]
> Could you try to set the `VIRTUALENVWRAPPER_PYTHON` before running `source /usr/local/bin/virtualenvwrapper.sh`?
> 
> For example:
> 
> ```
> VIRTUALENVWRAPPER_PYTHON='/usr/bin/python3'
> source /usr/local/bin/virtualenvwrapper.sh
> ```
> 
> This is an issue with virtualenvwrapper. I would recommend opening a ticket to the tool's tracker: https://bitbucket.org/virtualenvwrapper/virtualenvwrapper/issues?status=new&status=open
> 
> In case you do not plan to develop on top of Slither's API, I would recommend to not use virtualenv, and directly install Slither with:
> 
> ```
> pip3 install slither-analyzer
> ```

Moving `source /usr/local/bin/virtualenvwrapper.sh` below `VIRTUALENVWRAPPER_PYTHON='/usr/bin/python3'` worked for me!
