### ISSUE TITLE
Tuesday 22nd January: Slither discussion during Trail of Bits Office hours (12pm EST)  

### ISSUE THREAD

**Issue by montyly** [trailofbits/slither#130]
We will have a presentation about Slither during our next office hours session.

We will see how Slither works, what are its capacities, and what are our plans for its evolution.
If there is something you want to learn in particular about the framework, feel free to post a comment here, we will try to answer it during the call.

Our call will be [on google meet](https://meet.google.com/yjx-xhsa-ahz) on Tuesday 22nd Jan, 12pm EST ([5PM UTC](https://time.is/UTC)).

To follow our other office hours sessions, check our [calendar](https://calendar.google.com/calendar/embed?src=trailofbits.com_56jstkqe74aj76vv83q7h041q4%40group.calendar.google.com).

**Comment by aabdulwahed** [comment]
@montyly Are you going to publish this meeting on Youtube ?

**Comment by dguido** [comment]
@aabdulwahed https://www.youtube.com/watch?v=bakRWW05Uoc
