### ISSUE TITLE
Slither errors when you have a for loop within a for loop and break in the outer scope

### ISSUE THREAD

**Issue by Xenomega** [trailofbits/slither#141]
The following contract will crash slither:
```
contract C {
    function f() public {
        for(uint x = 0; x < 20; x++) {
            if(x == 10) {
                break;
            }
            for(uint i = 0; i < 20; i++) {
                // ...
            }
        }
    }
}
```

Note: The break statement does not need to be in the if-statement in order to cause this error. Moving the break into the inner loop will remove the error. Removing the inner for-loop will also remove the error.

Error:
```
ERROR:FunctionSolc:Break in no-loop context BREAK None
```

**Comment by montyly** [comment]
Fixed in https://github.com/trailofbits/slither/commit/29862ea54129800066d23c6585ac567ff93d94e6
