### ISSUE TITLE
Does not work with npm install'ed libraries

### ISSUE THREAD

**Issue by gakonst** [trailofbits/slither#168]
When running slither against repositories that use openzeppelin-solidity, e.g. a truffle repository, the usual command would be `slither contracts/`. 

For example, to compile contracts with solc that use `openzeppelin-solidity`, one must use the `--allow-paths` option as follows:

```
solc contractName.sol --allow-paths `pwd`/node_modules/openzeppelin-solidity openzeppelin-solidity=`pwd`/node_modules/openzeppelin-solidity
```

Slither in slither.py is parsing the commands, but [before passing the command to subprocess.Popen](https://github.com/trailofbits/slither/blob/master/slither/slither.py#L154), it fails to split the string at the `openzeppelin-solidity=...` bit, and thus passes the `openzeppelin-solidity=` part as part of the previous argument. This prevents it from passing the arguments to solc correctly, and thus is unable to compile. You can inspect this behavior by adding prints in L147-157 when solc_args is modified.

This can probably easily be fixed by tweaking the string parsing logic in https://github.com/trailofbits/slither/blob/master/slither/slither.py#L147-L157, but I didn't think of a good wy to do it

A nice UX upgrade would also be to grep through the contracts, and if it sees `openzeppelin-solidity` or `@aragon` for example, it should automatically include that in the `--allow-paths` logic.

**Comment by montyly** [comment]
If the repository uses truffle, you simply need to run `slither .` on the directory (and `npm install` or `yarn install` prior running slither, if the dependencies are not installed) 

Could you try if that solves the issue?

**Comment by gakonst** [comment]
Oh that works, did not realize you had added truffle support. 

It does not work however if I want to compile just a single contract without going into truffle mode (e.g I want the call-graph of just 1 contract without getting for all). Probably low priority issue though, thanks for the quick response.

**Comment by montyly** [comment]
Another solution is to export the json using solc directly: `solc --compact-ast-json __my_long_command_with_path_ > file.json` and to run Slither on `file.json`

Though I would not recommend to use solc directly on a Truffle project, as fighthing with `allow-paths` can take more time than just compiling everything with truffle, and exporting all the info.

**Comment by RyanRHall** [comment]
Ran into challenges getting slither to play nice with yarn. Since yarn hoists dependencies and doesn't necessarily keep them in the local node_modules folder, slither was unable to find 3rd party installed contracts. Would be nice to fix the `solc_args` option on slither so that the `--allow-paths` flag can be used to include other directories.

**Comment by igorline** [comment]
Same here! Does not work with lerna and yarn workspaces!

**Comment by Siegrift** [comment]
I had similar problems. I was using `openzeppelin` and `ensdomains` contracts from `node_modules` (and I used custom setup for solidity contracts).

I ended up using this hacky workaround using symbolic links and filtering the results:
```bash
#!/usr/bin/env bash

# slither has problems with imports in node_modules so we use symbolic link hack
ln -s ./node_modules/openzeppelin-solidity "openzeppelin-solidity"
ln -s ./node_modules/@ensdomains @ensdomains

# Redirect the output to stdout then exclude the results found in dependencies (--exclude-dependencies won't work here)
# and lastly, only include lines containing `.sol` with 1 line above each such finding.
slither . 2>&1 | grep -E -v "openzeppelin|@ensdomains" | grep -E -B 1 "\.sol#"

# cleanup
rm openzeppelin-solidity
rm @ensdomains
```

**Comment by montyly** [comment]
Hi @Siegrift 

Thank you for reporting this. Can you give a bit more context regarding the structure of the project? Is it open source? 

Additionally, what compilation platform are you using? (truffle, hardhat, something else?)

**Comment by Siegrift** [comment]
Hi, the project is https://github.com/district0x/name-bazaar 

We use clojurescript and have custom libraries for smart contracts deployments/testing - so it's completely custom :) 
We also have a "strange" project structure as smart contracts are located in `resources/public/contracts/src`

I also found out there are some false positives reported by this tool - most interesting one was `external-function` detector, which seemed to have problems with inheritance. I can create a separate issue for this if you want :)
