### ISSUE TITLE
Data dependency: use fix-point on function's context

### ISSUE THREAD

**Issue by montyly** [trailofbits/slither#171]
The data dependency uses a fix-point only at the contract's context, as a result, the function's context will miss some of the dependencies/taints

See: https://github.com/trailofbits/slither/issues/156#issuecomment-462095241

**Comment by montyly** [comment]
The issue is fixed in `master`.
We also added a new printer that should help to detect that kind of bug: [`data-dependency`](https://github.com/trailofbits/slither/wiki/Printer-documentation#data-dependencies).

There is still room for improvements to the data dependency (ex: better support for self-dependency, or better support of structure and mapping), and we are going to continue to improve it's accuracy.

**Comment by cty12** [comment]
Seems to work now. Thanks!
