### ISSUE TITLE
Error: Source file requires different compiler version

### ISSUE THREAD

**Issue by najienka** [trailofbits/slither#183]
Hi, 

I'm getting the following error. 
Do I need to use a particular solc version?

Many Thanks!

slither Events/ScalarEvent.sol --solc /usr/local/bin/solc
INFO:Slither:Compilation warnings/errors on Events/ScalarEvent.sol:
Events/ScalarEvent.sol:2:1: Error: Source file requires different compiler version (current compiler is 0.5.4+commit.9549d8ff.Darwin.appleclang - note that nightly builds are considered to be strictly less than the released version
import "../Events/Event.sol";
^----^

INFO:SlitherSolcParsing:No contract were found in Events/ScalarEvent.sol, check the correct compilation
WARNING:Slither:No contract was analyzed
INFO:Slither:Events/ScalarEvent.sol analyzed (0 contracts), 0 result(s) found

**Comment by montyly** [comment]
Hi,

Thank you for reporting the issue. 
It looks like an error with `solc`. Can you compile the contract with `solc` directly ?
```
solc Events/ScarEvent.sol
```
Maybe `../Events/Event.sol` requires a previous version of the compiler? 

Can you share the codebase?

Note that you can use [`solc-select`](https://github.com/trailofbits/solc-select) to quickly switch between solc versions.

**Comment by najienka** [comment]
Hi, 
Thanks for your swift response. 
Here is the codebase - I'm trying to use the tool on the gnosis smart contract project: https://github.com/gnosis/pm-contracts

but it still returns the same error.

Thanks

**Comment by montyly** [comment]
I see!
It is a Truffle project, and Slither supports Truffle natively. Run:
```
git clone https://github.com/gnosis/pm-contracts.git
cd pm-contracts
npm install
slither .
```
Slither will run `truffle compile` and all the detectors on the codebase.

For more advanced options, you can read the [Usage Documentation](https://github.com/trailofbits/slither/wiki/Usage).

**Comment by najienka** [comment]
Hi, Thanks for your help.
I've just tried this and got the following:

pm-contracts najienka$ slither .
INFO:Slither:'npx truffle@4.1.14 compile' running (use --truffle-version truffle@x.x.x to use specific version)
INFO:Slither:No local truffle config found. Using all defaults...

ERROR:Slither:npx: installed 82 in 3.295s

ERROR:SlitherSolcParsing:A contract was not found, it is likely that your codebase contains muliple contracts with the same name
ERROR:SlitherSolcParsing:Truffle does not handle this case during compilation
ERROR:SlitherSolcParsing:Please read https://github.com/trailofbits/slither/wiki#keyerror-or-nonetype-error
ERROR:SlitherSolcParsing:And update your code to remove the duplicate

**Comment by montyly** [comment]
Mhh strange, I just tried on a fresh directory and it does work.
What version of Slither are you using? `slither --version`

Could you try to delete the truffle build directory (`build` in `pm-contracts`)? Sometimes truffle does not clean properly previously compiled files and you might have conflicts because of that.

**Comment by najienka** [comment]
Thanks, deleting the build directory made it work! 

Quick question, how did you get your .png version of the dot file at https://github.com/trailofbits/slither/blob/master/examples/printers/call_graph.sol.dot.png

Is there any specific command to extract diagrams?
Thanks again

**Comment by dguido** [comment]
The ‘call-graph’ printer will create that for you.

**Comment by najienka** [comment]
Okay. 
At the moment this command `slither . --print call-graph` only creates the `.dot` file without a png.

**Comment by montyly** [comment]
You can use [`dot`](https://www.graphviz.org/) to generate the png file, as mentioned in the [printer documentation](https://github.com/trailofbits/slither/wiki/Printer-documentation#call-graph):
```
dot examples/printers/call_graph.sol.dot -Tsvg -o examples/printers/call_graph.sol.png
```

**Comment by najienka** [comment]
okay, thanks for your help.
