### ISSUE TITLE
Add detector modules equivalent to Manticore

### ISSUE THREAD

**Issue by dguido** [trailofbits/slither#5]
https://github.com/trailofbits/manticore/wiki/Ethereum-Detectors

- [ ] integer overflows
- [ ] invalid instructions
- [x] uninitialized memory
- [x] uninitialized storage
- [x] re-entrancy
- [x] re-entrancy (advanced)
- [x] unused return values
- [x] problematic delegatecalls
- [x] reachable selfdestruct
- [x] reachable externalcall
- [ ] potentially unsafe or manipulable instructions
- [ ] transaction order dependence

**Comment by dguido** [comment]
https://github.com/trailofbits/manticore/wiki/Ethereum-Detectors

**Comment by montyly** [comment]
Update of the issue:
-  `integer overflows`: slither needs precise numerical analysis for it; we are not yet here.
- `invalid instructions`: it does not make a lot of sense at the Solidity level.
- `unused return values`: https://github.com/trailofbits/slither/pull/68.
- `potentially unsafe or manipulable instructions`: a generic warning for 'unsafe' instructions won't give useful information to the dev imho. We have open detectors with more complex heuristics for some of the instructions (ex: `tx-origin`), some others are private. 
- `transaction order dependence`: A generic tod detector won't give useful information. I am waiting to see how Manticore update its detector to see what race condition detectors we will open source (https://github.com/trailofbits/manticore/issues/1260)

The other items are either in `master` or `dev` (the ones in `dev` need additional testing to improve the analysis confidence)

**Comment by montyly** [comment]
I think we can now close this issue. Most of the missing detectors are either included in Slither, or they don't make a lot of sense at the Solidity level
