### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'solc'

### ISSUE THREAD

**Issue by un1t** [trailofbits/slither#57]
I launch  program like this:

    slither Contract.sol 

and receive an error:
"FileNotFoundError: [Errno 2] No such file or directory: 'solc'"

I have solc installed.

    $ solcjs --version
    0.4.25+commit.59dbf8f1.Emscripten.clang

But executable is called **solcjs**, not **solc**. Or it is something different?

**Comment by redshark1802** [comment]
Yes, these are two different commands. Please follow the install instructions for solc https://solidity.readthedocs.io/en/v0.4.21/installing-solidity.html

**Comment by un1t** [comment]
Thank you!
I installed solc through apt-get, and now it works!

https://solidity.readthedocs.io/en/v0.4.21/installing-solidity.html#binary-packages

**Comment by dguido** [comment]
I added a troubleshooting section to capture questions and answers like this: https://github.com/trailofbits/slither/wiki#troubleshooting
