### ISSUE TITLE
Add support for yarn

### ISSUE THREAD

**Issue by dguido** [trailofbits/slither#77]
I'm not sure if we have to do anything special for it, but I've noticed a few projects are using yarn now. Here's a sample: https://github.com/SetProtocol/set-protocol-contracts

**Comment by cryptomental** [comment]
Hi @dguido this does not seem to apply to slither project. Yarn / npm is used for Node.js based packages and both tools consume package.json file.

**Comment by dguido** [comment]
So is this issue invalid? There's nothing we can or should do to help support build systems like the one in the set-protocol-contracts repo?
