### ISSUE TITLE
can't use xdot for slither

### ISSUE THREAD

**Issue by zxhubo** [trailofbits/slither#80]
Yes, I have been use xdot for slither to analyze contract with the for example in the wiki,but the result is 
```
38:Desktop bobby$ xdot wallet.sol.dot 

(xdot:70219): Gtk-WARNING **: 11:24:00.117: Error loading theme icon 'document-open' for stock: 图标“document-open”未在主题 Adwaita 中出现

(xdot:70219): Gtk-WARNING **: 11:24:00.169: Error loading theme icon 'view-refresh' for stock: 图标“view-refresh”未在主题 Adwaita 中出现

(xdot:70219): Gtk-WARNING **: 11:24:00.170: Error loading theme icon 'document-print' for stock: 图标“document-print”未在主题 Adwaita 中出现

(xdot:70219): Gtk-WARNING **: 11:24:00.170: Error loading theme icon 'zoom-in' for stock: 图标“zoom-in”未在主题 Adwaita 中出现

(xdot:70219): Gtk-WARNING **: 11:24:00.170: Error loading theme icon 'zoom-out' for stock: 图标“zoom-out”未在主题 Adwaita 中出现

dot: Not a directory
```

,and the for example is 

```
dot examples/printers/inheritances.sol.dot -Tsvg -o examples/printers/inheritances.sol.png
```
the result is `-bash: dot: command not found`
why? can U help me?

**Comment by zxhubo** [comment]
first the problem of "(xdot:70219): Gtk-WARNING **: 11:24:00.117: Error" ，reference `https://trac.macports.org/ticket/45229`，use command “brew install gnome-icon-theme” can resolve this problem。but I run  with command “xdot wallet.sol.dot ” ，the result is "dot: Not a directory" ? why ?

**Comment by zxhubo** [comment]
the second problem of “dot: Not a directory” ,I have been resolved, must install with this command "brew install graphviz" In MacBook . If use other system,use  other install command ,for example apt-get,yum .

**Comment by montyly** [comment]
Yes, you need to have both dot and xdot installed.
I have updated the guidelines for their installation here: https://github.com/trailofbits/slither/wiki#dot-command-not-found

Does that solve the issue?

**Comment by zxhubo** [comment]
@montyly Yep, thanks.
