### ISSUE TITLE
Add more details to JSON output

### ISSUE THREAD

**Issue by samparsky** [trailofbits/slither#91]
#### 1. If I have two contract definitions in a file e.g.
```javascript
contract C {
function i_am_backdoor(){}
}

contract D {
function i_am_backdoor(){
}
}
```
The json output doesn't tell me which of the contracts the function in the output belong to
The JSON output looks something like this
```js
{  
      "check":"backdoor",
      "function":{  
         "name":"i_am_a_backdoor",
         "source_mapping":{  
            "start":43,
            "length":74,
            "filename":"/tmp/browser/suicide.sol",
            "lines":[  
               5,
               6,
               7
            ]
         }
      }
   }
```
it doesn't indicate which contract it belongs to.

#### 2. Add Error Message
It would be great to have the error log messages displayed in the terminal as part of the JSON output.
The current implementation requires having to parse the details and reconstructing the messages.

These two changes are needed for the Slither Remix plugin

**Comment by montyly** [comment]
@samparsky Let me know if #94 fixes both issues

**Comment by samparsky** [comment]
@montyly There is no `description` field for `naming-convention` errors
