### ISSUE TITLE
Incorrect do-while CFG

### ISSUE THREAD

**Issue by krx** [trailofbits/slither#97]
The following loop outputs the wrong CFG
```
function dowhile() public {
    uint8 i = 0;
    uint8 a;
    do {
        i++;
        a = 1;
        a = 2;
        a = 3;
    } while (i < 10);
}
```

![out](https://user-images.githubusercontent.com/4693247/49768519-9dfc5600-fcaa-11e8-98fa-688042185473.png)

Correct output would look like this:
![out2](https://user-images.githubusercontent.com/4693247/49768651-077c6480-fcab-11e8-8f07-4168d23558d4.png)

**Comment by montyly** [comment]
Fixed in [master](https://github.com/trailofbits/slither/commit/39d88e119ac43416aa971b5aa80008ef6101e440)
